### ISSUE TITLE
Attachment of Policy to User gives error

### ISSUE THREAD

**Issue by divyaprakash18** [redradrat/aws-iam-operator#12]
While attaching the policy to user controller gives error and policy doesn't get attached. Users and Policies tested independently and no issue with them. Attachment of Policy to Role also works.

File:
```
apiVersion: aws-iam.redradrat.xyz/v1beta1
kind: PolicyAttachment
metadata:
  name: policyattachment-sample-dpy
  namespace: capabilities
spec:
  policy:
    name: policy-sample-test-dpy
    namespace: capabilities
  target:
    type: User
    name: user-dpy
    namespace: capabilities
```

Error on controller:
`ERROR	controller-runtime.controller	Reconciler error	{"controller": "policyattachment", "request": "default/policyattachment-sample-dpy", "error": "defined references do not exist for PolicyAttachment 'policyattachment-sample-dpy/default"}`
